# Welcome to Jekyll!

# Site Settings
locale                   : "en-US"
title                    : "Home"
name                     : "Guerrilla Epistemológica"
description              : "personal description"
url                      : https://arduinotomasi.github.io/guerrillaepistemologica
baseurl                  : ""
repository               : "arduinotomasi.github.io/guerrillaepistemologica"

# SEO Related
google_site_verification :  wIug60jUddg2K4FLuMzN-57Zea-AqH5K-AI4LzsSSzk

# Social Sharing
twitter:
  username               : "GEpistemologica"

# Site Author
author:
  name                   : "Guerrilla Epistemológica"
  avatar                 : "palacio.jpg"
  github                 : "arduinotomasi"
  twitter                : "GEpistemologica"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

